services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["sh", "/start.sh"]

  frontend:
    build:
      context: ./frontend
      env_file:
        - .env
    ports:
      - "4173:4173"

volumes:
  postgres_data:
